name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v14
        with:
          name: yuiyukihira
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v14
        with:
          name: yuiyukihira
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
